### PR TITLE
Use `emberjs-build`

### PR DESCRIPTION
**Pull request by seanpdoyle**
Extracts changes to `transpile-es6` back upstream

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@rwjblue all good over here :+1:

**Comment by rwjblue** [comment]
Merged upstream PR and released as v0.0.48.  Can you update and lock to the specific version?

**Comment by seanpdoyle** [comment]
@rwjblue :+1:

**Comment by seanpdoyle** [comment]
@rwjblue could we cut a release do I can continue my work on https://github.com/emberjs/ember.js/pull/10853

**Pull request merged**
