### PR TITLE
removeAttribute fix for IE <11 and svg

### LINKED ISSUE #251: IE <11 does not honor removeAttribute
Try it with viewBox: http://jsfiddle.net/2BqmC/2/

However setting the value of the attribute to `null` does seem to work at first glance. `domHelper.removeAttribute` needs to handle this browser bug.

### PR DESCRIPTION
**Pull request by mixonic**
Fixes #251

Old IE cannot remove svg attributes. Create a slow path for it.

### CODE REVIEW

**Comment by rwjblue** [comment]
@mixonic - Any progress on this?

**Comment by mixonic** [comment]
Need to make a map. Blah. Will wrap it this evening.

**Comment by mixonic** [comment]
This is good to go. Detecting this behavior is really hard, so I suggest we just make a narrow exception and grow the whitelist if needed.

**Comment by rwjblue** [comment]
@mixonic - Sounds good.  Will merge once Travis is happy.

**Comment by mixonic** [comment]
womp womp will fix tonight.

**Comment by rwjblue** [comment]
Travis failure is IE8 only (we recently removed it from the allowed failure list) on this test.

screenshot

**Pull request merged**
