### PR TITLE
quote 'yield' in lib/hooks

### PR DESCRIPTION
**Pull request by davidgoli**
Addresses https://github.com/tildeio/htmlbars/issues/420

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you add line comments mentioning yield as a reserved word on old android? I'm afraid that otherwise I might forget and remove this (since it looks "odd")...

**Comment by davidgoli** [comment]
@rwjblue done

**Comment by davidgoli** [comment]
wish there was a reliable way to test this...

**Comment by rwjblue** [comment]
We do test against sauce labs, not sure if they support these android versions though...

**Comment by rwjblue** [comment]
Sorry for the delay here. I guess we should release an updated version for Ember (for likely inclusion in Ember 2.2.1)

**Pull request merged**
