### PR TITLE
Remove IE8 workarounds

### PR DESCRIPTION
**Pull request by mmun**

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM 

@mixonic - r?

**Comment by mmun** [comment]
@mixonic Do you mind taking a peeking and checking if I missed anything? I only removed code near comments that explicitly mentioned IE8.

**Comment by mixonic** [comment]
:clap: this is great. Thanks @mmun!

**Comment by stefanpenner** [comment]
:shipit:

**Pull request merged**
