### PR TITLE
Report unfinished test runs correctly

### PR DESCRIPTION
**Pull request by johanneswuerbach**

### CODE REVIEW

**Comment by rwjblue** [comment]
What is this addressing?

**Comment by johanneswuerbach** [comment]
It looks like IE 8 never actually finished the tests (some js error on the way), but was reported as passing. I'm currently fixing that all browsers are marked as failed....

**Comment by rwjblue** [comment]
Gotcha, awesome!

**Comment by johanneswuerbach** [comment]
Fixed and moved IE 8 into the needs fixing section and IE 9 out.

**Comment by oneeman** [comment]
Thanks!  Should we also move IE 10 and 11 out of the allowed failure group?  They'll be passing after https://github.com/tildeio/htmlbars/pull/244 is merged, and hopefully we can keep them passing in the future.  IE 8 still needs work, though, like you say.

**Comment by johanneswuerbach** [comment]
@oneeman make sense to me

**Comment by oneeman** [comment]
Thanks, merged it now so we're back to a green build. @mmun will remove IE 10 and 11 from allowed failures since they're passing now too.

**Comment by mmun** [comment]
Done in #245.

**Pull request merged**
