### PR TITLE
Fix compile and run

### PR DESCRIPTION
**Pull request by chancancode**
Some recent changes broke compile-and-run, I think I fixed it! (see the commit messages for details about each change)

### CODE REVIEW

**Comment by chancancode** [comment]
By the way, attempting to invoke a non-existent helper (e.g. putting `{{#if ...}}` in the demo) now blows up with an `undefined.call(...)`. I haven't digged deep enough to know if that is expected or not. I might need to pass something more sophisticated than an empty POJO to `render`, unsure. But before my commit it was blowing up for a different reason (passing `undefined` as `helper`, so it did something like `undefined["if"]` in `lookupHelper`), so this is at least a partial fix.

**Comment by mmun** [comment]
Now that idempotent-rerender has been merged helpers should look the same across all "implementations" of HTMLBars. We could (should?) bake in the basic ones, (`if`, `each`, etc).

**Comment by chancancode** [comment]
Second pass: 

- [*] Fixed test
- [*] `bindSelf` to the data hash instead of copying its keys/values

Should be good to

**Comment by mmun** [comment]
Thanks. We really need to improve the top-level ergonomics :sweat_smile:

**Pull request merged**
