### PR TITLE
Update some build modules and fix jshint and bower errors 

### PR DESCRIPTION
**Pull request by g13013**
- Updated:
  - ember-cli
  - emberjs-build
  - broccoli-jshint
  - broccoli-funnel

- migrated `Brocfile.js` to `ember-cli-build.js`
- made JsHint ignore `morph-range` package
- fixed bower's `extra-resolution Unnecessary resolution: qunit#~1.18.0` warning

### CODE REVIEW

**Comment by rwjblue** [comment]
@chancancode mentioned previously that updating ember-cli caused issues so that change was reverted.  I'd like for him to confirm that those issues are fixed here (I don't believe he elaborated on what they were in the revert PR).

**Comment by g13013** [comment]
If it's the case and if you agree we could keep the build errors then

**Comment by g13013** [comment]
Even though I am asking myself if ember-cli is really necessary to build htmlbars?

**Comment by g13013** [comment]
I close for now, as things are not yet clear

**Pull request closed without merging**
