### PR TITLE
[Bugfix] fix props first logic

### PR DESCRIPTION
**Pull request by stefanpenner**
* for exceptions input.form, input.list, button.type always use setAttributes
* for form.action always escape
* always assign handlers to props, even if the case appears strange
* refactor normalizeProperty to return an object that clearly indicates type: & normalized:

### CODE REVIEW

**Comment by stefanpenner** [comment]
cc @jayphelps @mixonic

**Comment by stefanpenner** [comment]
hmm missing a test, 1 sec

**Comment by mixonic** [comment]
LGTM. Thanks for the effort on this tricky bit @stefanpenner!

**Comment by mixonic** [comment]
(Should be `[BUGFIX release]`)

**Comment by stefanpenner** [comment]
@wycats wanted to sync on this this afternoon.

**Comment by stefanpenner** [comment]
@mixonic updated

**Comment by stefanpenner** [comment]
@rwjblue 

> @wycats wanted to sync on this this afternoon.

**Comment by stefanpenner** [comment]
oh well, #yolo

**Pull request merged**
